// react/src/components/ModeButtons.tsx
type Mode = "text" | "image" | "video";

type ModeButtonsProps = {
  mode: Mode;
  setMode: React.Dispatch<React.SetStateAction<Mode>>;
  reset: () => void;
};

export default function ModeButtons({ mode, setMode, reset, }: ModeButtonsProps) {
  const changeMode = (nextMode: Mode): void => {
    setMode(nextMode);
    reset();
  };

  return (
    <div className="mode-buttons">
      <button
        className={mode === "text" ? "active" : ""}
        onClick={() => changeMode("text")}
      >
        Text
      </button>
      <button
        className={mode === "image" ? "active" : ""}
        onClick={() => changeMode("image")}
      >
        Image
      </button>
      <button
        className={mode === "video" ? "active" : ""}
        onClick={() => changeMode("video")}
      >
        Video
      </button>
    </div>
  );
}

// vue/src/components/ModeButtons.vue
<script setup lang="ts">
import type { Mode } from "../App.vue";

defineProps<{
  mode: Mode;
}>();

defineEmits<{
  (e: "change-mode", mode: Mode): void;
}>();
</script>

<template>
  <div class="mode-buttons">
    <button :class="{ active: mode === 'text' }" @click="$emit('change-mode', 'text')">
      Text
    </button>
    <button :class="{ active: mode === 'image' }" @click="$emit('change-mode', 'image')">
      Image
    </button>
    <button :class="{ active: mode === 'video' }" @click="$emit('change-mode', 'video')">
      Video
    </button>
  </div>
</template>
