// vue/src/components/MediaUploadBox.vue
<script setup lang="ts">
import type { Mode } from "../App.vue";
import type { Ref } from "vue";

defineProps<{
  mode: Mode;
  dragging: boolean;
  previewUrl: string;
  isPreviewLoading: boolean;
  accept: string;
  label: string;
  fileInput: Ref<HTMLInputElement | null>;
}>();

defineEmits<{
  (e: "open-file-picker"): void;
  (e: "drag-over", event: DragEvent): void;
  (e: "drag-leave"): void;
  (e: "drop-file", event: DragEvent): void;
  (e: "change-file", event: Event): void;
}>();
</script>

<template>
  <div
    class="upload-box"
    :class="{ dragging }"
    @click="!previewUrl ? $emit('open-file-picker') : undefined"
    @dragover="$emit('drag-over', $event)"
    @dragleave="$emit('drag-leave')"
    @drop="$emit('drop-file', $event)"
  >
    <input
      ref="fileInput"
      type="file"
      :accept="accept"
      @change="$emit('change-file', $event)"
      hidden
    />

    <div v-if="isPreviewLoading" class="media-loading">
      <span class="spinner dark"></span>
    </div>

    <img
      v-else-if="previewUrl && mode === 'image'"
      :src="previewUrl"
      alt="preview"
      class="media-preview"
    />

    <video
      v-else-if="previewUrl && mode === 'video'"
      :src="previewUrl"
      class="media-preview"
      controls
    />

    <div v-else class="upload-content">
      <div class="upload-icon">
        <svg
          v-if="mode === 'image'"
          width="88"
          height="88"
          viewBox="0 0 64 64"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <rect
            x="8"
            y="8"
            width="40"
            height="40"
            rx="4"
            stroke="currentColor"
            stroke-width="4"
          />
          <circle cx="20" cy="20" r="4" fill="currentColor" />
          <path
            d="M12 36L24 24L32 32L44 20L52 36"
            stroke="currentColor"
            stroke-width="4"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg>

        <svg
          v-else-if="mode === 'video'"
          width="88"
          height="88"
          viewBox="0 0 64 64"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <rect
            x="8"
            y="12"
            width="36"
            height="28"
            rx="4"
            stroke="currentColor"
            stroke-width="4"
          />
          <polygon points="22,20 22,32 32,26" fill="currentColor" />
        </svg>
      </div>

      <p class="upload-text">{{ label }}</p>
    </div>
  </div>
</template>

// react/front/src/components/MediaUploadBox.tsx
import ImageIcon from "../icons/ImageIcon";
import VideoIcon from "../icons/VideoIcon";

type Mode = "text" | "image" | "video";

type MediaUploadBoxProps = {
  mode: Mode;
  dragging: boolean;
  previewUrl: string;
  isPreviewLoading: boolean;
  getLabel: () => string;
  inputRef: React.RefObject<HTMLInputElement | null>;
  getAccept: () => string;
  openFilePicker: () => void;
  handleDragOver: (e: React.DragEvent<HTMLDivElement>) => void;
  handleDragLeave: () => void;
  handleDrop: (e: React.DragEvent<HTMLDivElement>) => Promise<void>;
  handleChange: (e: React.ChangeEvent<HTMLInputElement>) => Promise<void>;
};

export default function MediaUploadBox({
  mode,
  dragging,
  previewUrl,
  isPreviewLoading,
  getLabel,
  inputRef,
  getAccept,
  openFilePicker,
  handleDragOver,
  handleDragLeave,
  handleDrop,
  handleChange,
}: MediaUploadBoxProps) {
  return (
    <div
      className={`upload-box ${dragging ? "dragging" : ""}`}
      onClick={!previewUrl ? openFilePicker : undefined}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
    >
      <input
        ref={inputRef}
        type="file"
        accept={getAccept()}
        onChange={handleChange}
        hidden
      />

      {isPreviewLoading && (
        <div className="media-loading">
          <span className="spinner dark" />
        </div>
      )}

      {!isPreviewLoading && previewUrl && mode === "image" && (
        <img src={previewUrl} alt="preview" className="media-preview" />
      )}

      {!isPreviewLoading && previewUrl && mode === "video" && (
        <video src={previewUrl} className="media-preview" controls />
      )}

      {!isPreviewLoading && !previewUrl && (
        <div className="upload-content">
          <div className="upload-icon">
            {mode === "image" && <ImageIcon />}
            {mode === "video" && <VideoIcon />}
          </div>

          <p className="upload-text">{getLabel()}</p>
        </div>
      )}
    </div>
  );
}
