// vue/src/components/TextUploadBox.vue
<script setup lang="ts">
import type { Ref } from "vue";

defineProps<{
  dragging: boolean;
  text: string;
  accept: string;
  fileInput: Ref<HTMLInputElement | null>;
  textEditor: Ref<HTMLDivElement | null>;
}>();

defineEmits<{
  (e: "focus-editor"): void;
  (e: "open-file-picker"): void;
  (e: "drag-over", event: DragEvent): void;
  (e: "drag-leave"): void;
  (e: "drop-text", event: DragEvent): void;
  (e: "change-file", event: Event): void;
  (e: "input-text", event: Event): void;
  (e: "paste-text", event: ClipboardEvent): void;
}>();
</script>

<template>
  <div
    class="text-upload-box"
    :class="{ dragging }"
    @click="$emit('focus-editor')"
    @dragover="$emit('drag-over', $event)"
    @dragleave="$emit('drag-leave')"
    @drop="$emit('drop-text', $event)"
  >
    <input
      ref="fileInput"
      type="file"
      :accept="accept"
      @change="$emit('change-file', $event)"
      hidden
    />

    <div class="text-editor-wrap">
      <div
        v-if="!text"
        class="text-placeholder-row"
        @click.stop="$emit('focus-editor')"
      >
        <span class="text-placeholder">Paste your text, Drop or</span>
        <button
          type="button"
          class="inline-upload-btn"
          @click.stop="$emit('open-file-picker')"
        >
          Upload
        </button>
      </div>

      <div
        ref="textEditor"
        class="text-editable"
        :class="{ filled: text }"
        contenteditable
        @input="$emit('input-text', $event)"
        @paste="$emit('paste-text', $event)"
      ></div>
    </div>
  </div>
</template>

// react/front/src/components/TextUploadBox.tsx
type TextUploadBoxProps = {
  dragging: boolean;
  text: string;
  inputRef: React.RefObject<HTMLInputElement | null>;
  textRef: React.RefObject<HTMLDivElement | null>;
  getAccept: () => string;
  focusTextEditor: () => void;
  openFilePicker: () => void;
  handleDragOver: (e: React.DragEvent<HTMLDivElement>) => void;
  handleDragLeave: () => void;
  handleTextDrop: (e: React.DragEvent<HTMLDivElement>) => Promise<void>;
  handleChange: (e: React.ChangeEvent<HTMLInputElement>) => Promise<void>;
  handleTextInput: (e: React.FormEvent<HTMLDivElement>) => void;
  handleTextPaste: (e: React.ClipboardEvent<HTMLDivElement>) => void;
};

export default function TextUploadBox({
  dragging,
  text,
  inputRef,
  textRef,
  getAccept,
  focusTextEditor,
  openFilePicker,
  handleDragOver,
  handleDragLeave,
  handleTextDrop,
  handleChange,
  handleTextInput,
  handleTextPaste,
}: TextUploadBoxProps) {
  return (
    <div
      className={`text-upload-box ${dragging ? "dragging" : ""}`}
      onClick={focusTextEditor}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleTextDrop}
    >
      <input
        ref={inputRef}
        type="file"
        accept={getAccept()}
        onChange={handleChange}
        hidden
      />

      <div className="text-editor-wrap">
        {!text && (
          <div
            className="text-placeholder-row"
            onClick={(e: React.MouseEvent<HTMLDivElement>) => {
              e.stopPropagation();
              focusTextEditor();
            }}
          >
            <span className="text-placeholder">Paste your text, Drop or</span>
            <button
              type="button"
              className="inline-upload-btn"
              onClick={(e: React.MouseEvent<HTMLButtonElement>) => {
                e.stopPropagation();
                openFilePicker();
              }}
            >
              Upload
            </button>
          </div>
        )}

        <div
          ref={textRef}
          className={`text-editable ${text ? "filled" : ""}`}
          contentEditable
          suppressContentEditableWarning
          onInput={handleTextInput}
          onPaste={handleTextPaste}
        />
      </div>
    </div>
  );
}
