// vue/src/components/MediaResultPanel.vue
<script setup lang="ts">
defineProps<{
  result: string;
}>();

defineEmits<{
  (e: "reset"): void;
}>();
</script>

<template>
  <div class="analyze-section">
    <div class="analyze-button-row">
      <button type="button" class="reset-btn" @click="$emit('reset')">
        Reset
      </button>
    </div>

    <p v-if="result" class="result-text">{{ result }}</p>
  </div>
</template>

// react/src/components/MediaResultPanel.tsx
type MediaResultPanelProps = {
  previewUrl: string;
  isPreviewLoading: boolean;
  result: string;
  resetState: () => void;
};

export default function MediaResultPanel({
  previewUrl,
  isPreviewLoading,
  result,
  resetState,
}: MediaResultPanelProps) {
  if (!previewUrl || isPreviewLoading) return null;

  return (
    <div className="analyze-section">
      <div className="analyze-button-row">
        <button
          type="button"
          className="reset-btn"
          onClick={resetState}
        >
          Reset
        </button>
      </div>

      {result && <p className="result-text">{result}</p>}
    </div>
  );
}
