// vue/src/components/TextResultPanel.vue
<script setup lang="ts">
defineProps<{
  isAnalyzing: boolean;
  result: string;
}>();

defineEmits<{
  (e: "analyze"): void;
  (e: "reset"): void;
}>();
</script>

<template>
  <div class="analyze-section">
    <div class="analyze-button-row">
      <button
        class="analyze-btn"
        @click="$emit('analyze')"
        :disabled="isAnalyzing"
      >
        <span v-if="isAnalyzing" class="spinner"></span>
        <span v-else>Analyze</span>
      </button>

      <button
        v-if="result"
        type="button"
        class="reset-btn"
        @click="$emit('reset')"
      >
        Reset
      </button>
    </div>

    <p v-if="result" class="result-text">{{ result }}</p>
  </div>
</template>

// react/src/components/TextResultPanel.tsx
type TextResultPanelProps = {
  text: string;
  isAnalyzing: boolean;
  result: string;
  handleAnalyze: () => Promise<void>;
  resetState: () => void;
};

export default function TextResultPanel({
  text,
  isAnalyzing,
  result,
  handleAnalyze,
  resetState,
}: TextResultPanelProps) {
  if (!text.trim()) return null;

  return (
    <div className="analyze-section">
      <div className="analyze-button-row">
        <button
          className="analyze-btn"
          onClick={handleAnalyze}
          disabled={isAnalyzing}
        >
          {isAnalyzing ? <span className="spinner" /> : "Analyze"}
        </button>

        {result && (
          <button
            type="button"
            className="reset-btn"
            onClick={resetState}
          >
            Reset
          </button>
        )}
      </div>

      {result && <p className="result-text">{result}</p>}
    </div>
  );
}
